apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-01
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-pod-01
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: account
      readOnly: true
  volumes:
  - name: account
    secret:
      secretName: secret-account
      items:
      - key: account_key
        path: index.html
